import {
  type Locale,
  type RouteKey,
  LOCALES,
  DEFAULT_LOCALE,
  localizedPath,
} from "@/lib/routes"

// Canonical host is www: production 308-redirects the apex to www, and the
// Google Search Console property is verified on www. Keep this in sync with
// NEXT_PUBLIC_SITE_URL in Vercel and the redirect at the edge — every
// canonical/sitemap/robots URL derives from here.
export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.araguaney.org"
).replace(/\/$/, "")

// El dominio que lee una persona: pies de página, direcciones de contacto,
// llms.txt. Sale de SITE_URL para que mudar de dominio (Fase 29) sea cambiar
// una variable en Vercel y no buscar y reemplazar texto.
export const SITE_DOMAIN = new URL(SITE_URL).hostname.replace(/^www\./, "")

// Una dirección de contacto del dominio público (`hola`, `privacidad`, …). Esos
// buzones tienen que existir en el dominio antes de cambiarlo.
export function contactEmail(localPart: string): string {
  return `${localPart}@${SITE_DOMAIN}`
}

// Single source of truth for the brand entity's `sameAs` links — the
// authoritative external profiles Google/AI use to resolve the entity in the
// knowledge graph. Empty until the accounts exist: add each official URL here
// (LinkedIn, GitHub, X, Instagram, Crunchbase) and, once created, the Wikidata
// entity URL (Fase 17 task 6). They flow into the Organization schema
// automatically — only rendered when non-empty. See Fase 17 task 5.
export const BRAND_SAME_AS: readonly string[] = [
  "https://www.linkedin.com/company/araguaney-lat",
  "https://github.com/araguaney-org",
]

// Repositorio público y licencia. El código abierto es una señal de confianza
// verificable: cualquiera puede auditar que no se guardan datos personales.
export const SOURCE_REPO_URL = "https://github.com/araguaney-org/araguaney"
export const LICENSE_URL = "https://www.gnu.org/licenses/agpl-3.0.html"
export const LICENSE_NAME = "AGPL-3.0"

// Public founder attribution for the Organization `founder` (E-E-A-T signal).
export const BRAND_FOUNDING_YEAR = "2026"

// Identidad pública del fundador. `sameAs` es el perfil externo que permite a
// buscadores y motores de respuesta resolver a la persona como entidad; el rol
// va por locale porque también se renderiza como texto visible en /nosotros.
export const FOUNDER = {
  name: "Antony Delgado",
  url: "https://www.linkedin.com/in/adelgadox/",
  sameAs: ["https://www.linkedin.com/in/adelgadox/"] as readonly string[],
  jobTitle: {
    es: "Ingeniero de Software y responsable de la plataforma",
    en: "Software Engineer, responsible for the platform",
  },
} as const

export function absoluteUrl(path: string): string {
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`
}

// Shared default share image. Next.js metadata does NOT deep-merge nested
// objects (openGraph, twitter) between layout.tsx and a page's own metadata —
// a page defining `openGraph: { title, description }` completely REPLACES
// the layout's `openGraph`, silently dropping `images`. Every page that
// defines its own openGraph/twitter metadata must re-include this image
// (or its own) explicitly; it will not fall back to the layout's.
export const DEFAULT_OG_IMAGE =
  "https://res.cloudinary.com/dtvdqlxtd/image/upload/w_1200,h_630,c_pad,b_white,f_png/v1782786243/araguaney_logo_ol8lm1"

// Branded per-page share card generated by app/og/route.tsx. Pass a page title
// (and optional eyebrow) to get its own Open Graph image instead of the logo.
export function ogImageUrl(title: string, eyebrow?: string): string {
  const params = new URLSearchParams({ title })
  if (eyebrow) params.set("eyebrow", eyebrow)
  return absoluteUrl(`/og?${params.toString()}`)
}

// Canonical + hreflang alternates for a migrated route, for `metadata.alternates`.
// Emits one `hreflang` per supported locale plus `x-default` (the default locale).
// Paths are relative; Next resolves them against metadataBase. Generic over
// LOCALES so a new language is included automatically.
export function alternates(key: RouteKey, locale: string) {
  const languages: Record<string, string> = {}
  for (const l of LOCALES) {
    languages[l] = localizedPath(key, l)
  }
  languages["x-default"] = localizedPath(key, DEFAULT_LOCALE)
  return {
    canonical: localizedPath(key, locale),
    languages,
  }
}
